spring:
  kafka:
    producer:
      bootstrap-servers:  bobo1:9092,bobo2:9092,bobo3:9092
      retries:  0
      batch-size:  4096
      buffer-memory: 40960
      linger: 1   # 1秒钟发送一次
      acks: 1
      partition-number: 3
      replication-factor: 2
      metadata-max-age-ms:  10000
    consumer:
      bootstrap-servers: bobo1:9092,bobo2:9092,bobo3:9092
      group-id:  smf-test
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest
      session-timeout: 6000
      concurrency: 10
